// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GorpMigrations string
	Items          string
}{
	GorpMigrations: "gorp_migrations",
	Items:          "items",
}
